retail:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: airflowetl-425915  
      dataset: retail             
      keyfile: C:/Users/etlda/airflow_etl/gcp/service_account.json 
      threads: 1
      timeout_seconds: 300
      location: US
      priority: interactive
      retries: 1
