retail:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: airflowetl-426020  
      dataset: retail             
      keyfile: /opt/airflow/gcp/service_account.json 
      threads: 1
      timeout_seconds: 300
      location: US
      priority: interactive
      retries: 1
